name: Workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci_module_cpp20_ubuntu:
    strategy:
      matrix:
        container: ['gcc:latest', 'silkeh/clang:latest']
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - name: Install needed tools
        run: apt-get update ; apt-get install -y unzip
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@ea004816823209b8d1211e47b216185caee12cc5 # v4.02
      - name: Run CMake
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build

  ci_module_cpp20_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run CMake (Debug)
        run: cmake -S . -B build -G "Visual Studio 17 2022" -DCMAKE_CXX_FLAGS="/permissive- /std:c++latest /utf-8 /W4 /WX"
      - name: Build
        run: cmake --build build --config Debug
